from iacs_profile.iacs_caaml_types import IACSGrainShapeType, IACSHardnessType, IACSLiquidWaterContentType

IACS_GRAIN_SHAPE_TYPE_DICT = {
    IACSGrainShapeType.PP: "P",
    IACSGrainShapeType.PP_CO: "o",
    IACSGrainShapeType.PP_ND: "n",
    IACSGrainShapeType.PP_PL: "m",
    IACSGrainShapeType.PP_SD: "s",
    IACSGrainShapeType.PP_IR: "i",
    IACSGrainShapeType.PP_GP: "g",
    IACSGrainShapeType.PP_HL: "l",
    IACSGrainShapeType.PP_IP: "q",
    IACSGrainShapeType.PP_RM: "t",
    IACSGrainShapeType.MM: "M",
    IACSGrainShapeType.MM_RP: "M",
    IACSGrainShapeType.MM_CI: "a",
    IACSGrainShapeType.DF: "C",
    IACSGrainShapeType.DF_DC: "C",
    IACSGrainShapeType.DF_BK: "b",
    IACSGrainShapeType.RG: "R",
    IACSGrainShapeType.RG_SR: "j",
    IACSGrainShapeType.RG_LG: "R",
    IACSGrainShapeType.RG_WP: "w",
    IACSGrainShapeType.RG_XF: "y",
    IACSGrainShapeType.FC: "F",
    IACSGrainShapeType.FC_SO: "F",
    IACSGrainShapeType.FC_SF: "f",
    IACSGrainShapeType.FC_XR: "r",
    IACSGrainShapeType.DH: "D",
    IACSGrainShapeType.DH_CP: "D",
    IACSGrainShapeType.DH_PR: "p",
    IACSGrainShapeType.DH_CH: "h",
    IACSGrainShapeType.DH_LA: "k",
    IACSGrainShapeType.DH_XR: "x",
    IACSGrainShapeType.SH: "S",
    IACSGrainShapeType.SH_SU: "S",
    IACSGrainShapeType.SH_CV: "v",
    IACSGrainShapeType.SH_XR: "u",
    IACSGrainShapeType.MF: "N",
    IACSGrainShapeType.MF_CL: "z",
    IACSGrainShapeType.MF_PC: "{",
    IACSGrainShapeType.MF_SL: "|",
    IACSGrainShapeType.MF_CR: "}",
    IACSGrainShapeType.IF: "I",
    IACSGrainShapeType.IF_IL: "I",
    IACSGrainShapeType.IF_IC: "d",
    IACSGrainShapeType.IF_BI: "e",
    IACSGrainShapeType.IF_RC: "~",
    IACSGrainShapeType.IF_SC: "["
}

IACS_HARDNESS_TYPE_DICT = {
    IACSHardnessType.F_MINUS: "_-",
    IACSHardnessType.F: "_",
    IACSHardnessType.F_PLUS: "_+",
    IACSHardnessType.FF4: "_-2",
    IACSHardnessType.F4_MINUS: "2-",
    IACSHardnessType.F4: "2",
    IACSHardnessType.F4_PLUS: "2+",
    IACSHardnessType.F4F1: "2-3",
    IACSHardnessType.F1_MINUS: "3-",
    IACSHardnessType.F1: "3",
    IACSHardnessType.F1_PLUS: "3+",
    IACSHardnessType.F1P: "3-4",
    IACSHardnessType.P_MINUS: "4-",
    IACSHardnessType.P: "4",
    IACSHardnessType.P_PLUS: "4+",
    IACSHardnessType.PK: "4-5",
    IACSHardnessType.K_MINUS: "5-",
    IACSHardnessType.K: "5",
    IACSHardnessType.K_PLUS: "5+",
    IACSHardnessType.KI: "5-I",
    IACSHardnessType.I: "I"

}

IACS_LIQUID_WATER_CONTENT_TYPE_DICT = {
    IACSLiquidWaterContentType.D: "_",
    IACSLiquidWaterContentType.DM: "_-U",
    IACSLiquidWaterContentType.M: "U",
    IACSLiquidWaterContentType.MW: "U-V",
    IACSLiquidWaterContentType.W: "V",
    IACSLiquidWaterContentType.WV: "V-W",
    IACSLiquidWaterContentType.V: "W",
    IACSLiquidWaterContentType.VS: "W-X",
    IACSLiquidWaterContentType.S: "X"

}
